--[[
  WezMacs Global Configuration

  This file contains global WezMacs settings.
  These values override defaults from wezmacs/config.lua

  Available settings:
    color_scheme - Color scheme name (string, nil for default)
    mod_key - Modifier key ("CMD", "ALT", "CTRL", "SHIFT")
    leader_key - Leader key (string, e.g., "Space")
    leader_mod - Leader modifier ("CMD", "ALT", "CTRL", "SHIFT")

  Modules can access these via:
    local wezmacs = require('wezmacs')
    print(wezmacs.config.color_scheme)

  Generated by: wezmacs/generate-config.lua
]]

return {
	term_mod = "LEADER",
}
