--[[
  WezMacs Global Configuration

  This file contains global WezMacs settings.
  These values override defaults from wezmacs/config.lua

  Available settings:
    font_size - Font size (number, e.g., 12.0)
    font_family - Font family name (string, nil for default)
    color_scheme - Color scheme name (string, nil for default)
    mod_key - Modifier key ("CMD", "ALT", "CTRL", "SHIFT")
    leader_key - Leader key (string, e.g., "Space")
    leader_mod - Leader modifier ("CMD", "ALT", "CTRL", "SHIFT")

  Modules can access these via:
    local wezmacs = require('wezmacs')
    print(wezmacs.config.font_size)

  Generated by: wezmacs/generate-config.lua
]]

return {
  -- font_size = 12.0,
  -- font_family = nil,  -- nil = use WezTerm default
  -- color_scheme = nil,  -- nil = use WezTerm default
  -- mod_key = "CMD",
  -- leader_key = "Space",
  -- leader_mod = "CTRL",
}
