--[[
  WezMacs Modules Configuration

  This file lists which modules to load.
  Each entry can be:
    - A string: "module-name" (enables module with default options)
    - A table: { "module-name", opts = { ... }, keys = { ... } }

  Examples:
    "core"  -- Enable core module
    { "git", opts = { leader_key = "G" } }  -- Enable git with custom options
    { "claude", keys = { LEADER = { c = { action = ..., desc = "..." } } } }  -- Override keys

  Generated by: wezmacs/generate-config.lua
]]

return {
  "claude",
  "core",
  "docker",
  "domains",
  "editors",
  "file-manager",
  "fonts",
  "git",
  "keybindings",
  "kubernetes",
  "media",
  "mouse",
  "system-monitor",
  "tabbar",
  "theme",
  "window",
  "workspace",
}
