--[[
  WezMacs Modules Configuration

  This file lists which modules to load.
  Each entry can be:
    - A string: "module-name" (enables module with default options)
    - A table: { "module-name", opts = { ... }, keys = { ... } }

  Examples:
    "term"  -- Enable term module
    { "git", opts = { leader_key = "G" } }  -- Enable git with custom options
    { "agent", keys = { LEADER = { a = { action = ..., desc = "..." } } } }  -- Override keys

  Generated by: wezmacs/generate-config.lua
]]

return {
	"app",
	"mouse",
	{
		"term",
		opts = {
			font = "Iosevka Mono",
			font_size = 24,
		},
	},
	{
		"window",
		opts = {
			font = "Iosevka",
			font_size = 18,
		},
	},
	{ "tabs" },
	{
		"mux",
		opts = {
			term_mod = "CTRL|SHIFT",
			term_alt_mod = "CTRL|SHIFT|ALT",
		},
	},
	{
		"edit",
		opts = {
			editor = "hx",
			ide = "cursor",
		},
	},
	"git",
	"agent",
}
