#!/usr/bin/env lua
--[[
  WezMacs Config Generator

  Generates a user configuration file by scanning all modules and reading their
  init.lua files (LazyVim-style: init.lua returns spec table with opts, description, category).

  Usage:
    lua wezmacs/generate-config.lua [output_path]

  Output path defaults to ~/.config/wezmacs/wezmacs.lua
]]

local function get_home_dir()
  return os.getenv("HOME") or os.getenv("USERPROFILE")
end

local function get_config_dir()
  local xdg_config = os.getenv("XDG_CONFIG_HOME")
  if xdg_config then
    return xdg_config
  end
  return get_home_dir() .. "/.config"
end

local function file_exists(path)
  local f = io.open(path, "r")
  if f then
    f:close()
    return true
  end
  return false
end

local function read_file(path)
  local f = io.open(path, "r")
  if not f then
    return nil
  end
  local content = f:read("*all")
  f:close()
  return content
end

local function get_modules_dir()
  -- Assume script is in wezmacs/ directory
  local script_path = arg[0]
  local script_dir = script_path:match("^(.+)/[^/]+$") or "."
  return script_dir .. "/modules"
end

local function scan_modules()
  local modules_dir = get_modules_dir()
  local modules = {}
  
  -- Set up package.path to find wezmacs modules
  local script_dir = arg[0]:match("^(.+)/[^/]+$") or "."
  local wezmacs_dir = script_dir:match("^(.+)/[^/]+$") or script_dir
  local old_path = package.path
  package.path = wezmacs_dir .. "/?.lua;" .. wezmacs_dir .. "/?/init.lua;" .. package.path

  -- Use ls to get module files (single .lua files, not directories)
  local handle = io.popen("ls -1 '" .. modules_dir .. "' | grep '\\.lua$'")
  if not handle then
    package.path = old_path
    error("Failed to list modules directory: " .. modules_dir)
  end

  for file in handle:lines() do
    local mod_name = file:match("^(.+)%.lua$")
    if mod_name then
      -- Load module file (LazyVim-style: returns spec table directly)
      local require_path = "wezmacs.modules." .. mod_name
      local spec_ok, spec = pcall(require, require_path)
      
      if spec_ok and type(spec) == "table" and spec.name then
        local module_info = {
          name = spec.name or dir,
          description = spec.description or "",
          category = spec.category or "integration",
          opts = spec.opts or {},
        }
        
        -- Extract features from opts
        module_info.features = {}
        if module_info.opts.features then
          for feature_name, _ in pairs(module_info.opts.features) do
            table.insert(module_info.features, feature_name)
          end
        end
        
        table.insert(modules, module_info)
      end
    end
  end

  handle:close()
  package.path = old_path

  -- Sort modules by name
  table.sort(modules, function(a, b)
    return a.name < b.name
  end)

  return modules
end

local function generate_config(modules)
  local lines = {
    "--[[",
    "  WezMacs Configuration",
    "",
    "  This file configures all WezMacs modules. Each module is listed below",
    "  with its available options and default values.",
    "",
    "  Configuration locations (priority order):",
    "    1. ~/.wezmacs.lua",
    "    2. ~/.config/wezmacs/wezmacs.lua",
    "",
    "  Generated by: wezmacs/generate-config.lua",
    "  Edit this file to customize your configuration.",
    "]]",
    "",
    "return {",
  }

  -- Group modules by category (heuristic: check first word of description)
  local categories = {
    core = {},
    ui = {},
    behavior = {},
    editing = {},
    workflows = {},
    tools = {},
    integration = {},
  }

  for _, mod in ipairs(modules) do
    -- Use category from spec, fallback to heuristic
    local category = mod.category or "integration"
    if not categories[category] then
      category = "integration"  -- Fallback if category doesn't exist
    end
    table.insert(categories[category], mod)
  end

  -- Generate config sections
  local category_names = {
    core = "Core Settings",
    ui = "UI Modules",
    behavior = "Behavior Modules",
    editing = "Editing Modules",
    workflows = "Workflow Modules",
    tools = "Tool Modules",
    integration = "Integration Modules",
  }

  local category_order = {"core", "ui", "behavior", "editing", "workflows", "tools", "integration"}

  for _, cat_key in ipairs(category_order) do
    local cat_modules = categories[cat_key]
    if #cat_modules > 0 then
      table.insert(lines, "  -- " .. category_names[cat_key])
      for _, mod in ipairs(cat_modules) do
        if mod.description then
          table.insert(lines, "  -- " .. mod.description)
        end
        -- Quote module name if it contains hyphens
        local module_key = mod.name
        if module_key:match("-") then
          module_key = '["' .. module_key .. '"]'
        end
        table.insert(lines, "  " .. module_key .. " = {")

        -- Generate opts fields
        if mod.opts then
          for field, value in pairs(mod.opts) do
            if field ~= "features" then  -- Features handled separately
              local value_str
              if type(value) == "string" then
                value_str = '"' .. value .. '"'
              elseif type(value) == "nil" then
                value_str = "nil"
              elseif type(value) == "boolean" then
                value_str = tostring(value)
              elseif type(value) == "number" then
                value_str = tostring(value)
              else
                value_str = "-- " .. type(value) .. " (see module init.lua for details)"
              end
              table.insert(lines, "    -- " .. field .. " = " .. value_str .. ",")
            end
          end
        end

        if mod.features and #mod.features > 0 then
          table.insert(lines, "")
          table.insert(lines, "    -- Optional features:")
          for _, feature in ipairs(mod.features) do
            table.insert(lines, "    -- features." .. feature .. " = { enabled = true },")
          end
        end

        table.insert(lines, "  },")
        table.insert(lines, "")
      end
    end
  end

  table.insert(lines, "}")
  table.insert(lines, "")

  return table.concat(lines, "\n")
end

local function main()
  local output_path = arg[1]
  if not output_path then
    output_path = get_config_dir() .. "/wezmacs/wezmacs.lua"
  end

  print("Scanning modules...")
  local modules = scan_modules()
  print("Found " .. #modules .. " modules")

  print("Generating configuration...")
  local config = generate_config(modules)

  -- Create directory if needed
  local output_dir = output_path:match("^(.+)/[^/]+$")
  if output_dir then
    os.execute("mkdir -p '" .. output_dir .. "'")
  end

  print("Writing configuration to: " .. output_path)
  local f = io.open(output_path, "w")
  if not f then
    error("Failed to open output file: " .. output_path)
  end
  f:write(config)
  f:close()

  print("✓ Configuration generated successfully")
  print("")
  print("Next steps:")
  print("1. Edit " .. output_path .. " to customize your configuration")
  print("2. Reload WezTerm (Cmd+Option+R on macOS)")
end

main()
