#!/usr/bin/env lua
--[[
  WezMacs Config Generator

  Generates a user configuration file by scanning all modules and reading their
  metadata (_CONFIG_SCHEMA, _FEATURES, _DESCRIPTION).

  Usage:
    lua wezmacs/generate-config.lua [output_path]

  Output path defaults to ~/.config/wezmacs/wezmacs.lua
]]

local function get_home_dir()
  return os.getenv("HOME") or os.getenv("USERPROFILE")
end

local function get_config_dir()
  local xdg_config = os.getenv("XDG_CONFIG_HOME")
  if xdg_config then
    return xdg_config
  end
  return get_home_dir() .. "/.config"
end

local function file_exists(path)
  local f = io.open(path, "r")
  if f then
    f:close()
    return true
  end
  return false
end

local function read_file(path)
  local f = io.open(path, "r")
  if not f then
    return nil
  end
  local content = f:read("*all")
  f:close()
  return content
end

local function get_modules_dir()
  -- Assume script is in wezmacs/ directory
  local script_path = arg[0]
  local script_dir = script_path:match("^(.+)/[^/]+$") or "."
  return script_dir .. "/modules"
end

local function scan_modules()
  local modules_dir = get_modules_dir()
  local modules = {}

  -- Use ls to get module directories
  local handle = io.popen("ls -1 '" .. modules_dir .. "'")
  if not handle then
    error("Failed to list modules directory: " .. modules_dir)
  end

  for dir in handle:lines() do
    local init_path = modules_dir .. "/" .. dir .. "/init.lua"
    if file_exists(init_path) then
      local content = read_file(init_path)
      if content then
        local module_info = {
          name = dir,
          path = init_path,
        }

        -- Extract _DESCRIPTION
        local desc = content:match('M%._DESCRIPTION%s*=%s*"([^"]+)"')
        if desc then
          module_info.description = desc
        end

        -- Extract _CONFIG (unified structure)
        local config_start = content:find("M%._CONFIG%s*=%s*{")
        if config_start then
          local brace_count = 0
          local in_config = false
          local config_text = ""
          for i = config_start, #content do
            local char = content:sub(i, i)
            if char == "{" then
              brace_count = brace_count + 1
              in_config = true
            elseif char == "}" then
              brace_count = brace_count - 1
            end
            if in_config then
              config_text = config_text .. char
            end
            if in_config and brace_count == 0 then
              break
            end
          end

          -- Parse config fields (basic regex - captures top-level keys)
          module_info.config = {}
          module_info.features = {}

          -- Look for top-level fields
          for field, value in config_text:gmatch('\n%s+([%w_]+)%s*=%s*([^,\n]+)') do
            local trimmed = value:gsub("^%s+", ""):gsub("%s+$", "")
            module_info.config[field] = trimmed
          end

          -- Look for feature definitions (fields with enabled = false/true)
          for feature_name in config_text:gmatch('\n%s+([%w_]+)%s*=%s*{[^}]*enabled%s*=') do
            table.insert(module_info.features, feature_name)
          end
        end

        table.insert(modules, module_info)
      end
    end
  end

  handle:close()

  -- Sort modules by name
  table.sort(modules, function(a, b)
    return a.name < b.name
  end)

  return modules
end

local function generate_config(modules)
  local lines = {
    "--[[",
    "  WezMacs Configuration",
    "",
    "  This file configures all WezMacs modules. Each module is listed below",
    "  with its available options and default values.",
    "",
    "  Configuration locations (priority order):",
    "    1. ~/.wezmacs.lua",
    "    2. ~/.config/wezmacs/wezmacs.lua",
    "",
    "  Generated by: wezmacs/generate-config.lua",
    "  Edit this file to customize your configuration.",
    "]]",
    "",
    "return {",
  }

  -- Group modules by category (heuristic: check first word of description)
  local categories = {
    core = {},
    ui = {},
    behavior = {},
    editing = {},
    workflows = {},
    tools = {},
    integration = {},
  }

  for _, mod in ipairs(modules) do
    local category = "integration" -- default
    if mod.name == "core" then
      category = "core"
    elseif mod.description then
      local desc_lower = mod.description:lower()
      if desc_lower:match("color") or desc_lower:match("font") or desc_lower:match("tab") or desc_lower:match("window") or desc_lower:match("visual") then
        category = "ui"
      elseif desc_lower:match("mouse") or desc_lower:match("scroll") then
        category = "behavior"
      elseif desc_lower:match("key") or desc_lower:match("edit") then
        category = "editing"
      elseif desc_lower:match("git") or desc_lower:match("workspace") or desc_lower:match("claude") then
        category = "workflows"
      elseif desc_lower:match("docker") or desc_lower:match("kubernetes") or desc_lower:match("file") or desc_lower:match("editor") or desc_lower:match("system") or desc_lower:match("media") then
        category = "tools"
      end
    end
    table.insert(categories[category], mod)
  end

  -- Generate config sections
  local category_names = {
    core = "Core Settings",
    ui = "UI Modules",
    behavior = "Behavior Modules",
    editing = "Editing Modules",
    workflows = "Workflow Modules",
    tools = "Tool Modules",
    integration = "Integration Modules",
  }

  local category_order = {"core", "ui", "behavior", "editing", "workflows", "tools", "integration"}

  for _, cat_key in ipairs(category_order) do
    local cat_modules = categories[cat_key]
    if #cat_modules > 0 then
      table.insert(lines, "  -- " .. category_names[cat_key])
      for _, mod in ipairs(cat_modules) do
        if mod.description then
          table.insert(lines, "  -- " .. mod.description)
        end
        table.insert(lines, "  " .. mod.name .. " = {")

        if mod.schema then
          for field, value in pairs(mod.schema) do
            table.insert(lines, "    -- " .. field .. " = " .. value .. ",")
          end
        end

        if mod.has_features then
          table.insert(lines, "    -- Feature flags:")
          table.insert(lines, "    -- feature_name = {},")
        end

        table.insert(lines, "  },")
        table.insert(lines, "")
      end
    end
  end

  table.insert(lines, "}")
  table.insert(lines, "")

  return table.concat(lines, "\n")
end

local function main()
  local output_path = arg[1]
  if not output_path then
    output_path = get_config_dir() .. "/wezmacs/wezmacs.lua"
  end

  print("Scanning modules...")
  local modules = scan_modules()
  print("Found " .. #modules .. " modules")

  print("Generating configuration...")
  local config = generate_config(modules)

  -- Create directory if needed
  local output_dir = output_path:match("^(.+)/[^/]+$")
  if output_dir then
    os.execute("mkdir -p '" .. output_dir .. "'")
  end

  print("Writing configuration to: " .. output_path)
  local f = io.open(output_path, "w")
  if not f then
    error("Failed to open output file: " .. output_path)
  end
  f:write(config)
  f:close()

  print("✓ Configuration generated successfully")
  print("")
  print("Next steps:")
  print("1. Edit " .. output_path .. " to customize your configuration")
  print("2. Reload WezTerm (Cmd+Option+R on macOS)")
end

main()
