#!/usr/bin/env lua
--[[
  WezMacs Config Generator

  Generates user configuration files in the new format:
  - config.lua: Module overrides (list format)
  - setup.lua: Custom setup function
  - keys.lua: Custom keybindings

  Usage:
    lua lua/generate-config.lua [output_directory]

  Output directory defaults to ~/.config/wezmacs/
]]

local function get_home_dir()
  return os.getenv("HOME") or os.getenv("USERPROFILE")
end

local function get_config_dir()
  local xdg_config = os.getenv("XDG_CONFIG_HOME")
  if xdg_config then
    return xdg_config .. "/wezmacs"
  end
  return get_home_dir() .. "/.config/wezmacs"
end

local function get_lua_dir()
  -- Get directory containing this script (lua/generate-config.lua)
  local script_path = arg[0]
  local script_dir
  
  -- Handle both absolute and relative paths
  if script_path:match("^/") then
    -- Absolute path
    script_dir = script_path:match("^(.+)/[^/]+$")
  else
    -- Relative path - resolve from current working directory
    local cwd = io.popen("pwd"):read("*l")
    if script_path:match("^lua/") then
      -- Script path is relative like "lua/generate-config.lua"
      script_dir = cwd .. "/lua"
    else
      -- Script path is just filename, assume lua/ directory
      script_dir = cwd .. "/lua"
    end
  end
  
  return script_dir
end

local function scan_modules()
  local modules = {}
  local lua_dir = get_lua_dir()
  local modules_dir = lua_dir .. "/modules"

  -- Use ls to get module files (single .lua files, not directories)
  local handle = io.popen("ls -1 '" .. modules_dir .. "' 2>/dev/null | grep '\\.lua$'")
  if not handle then
    error("Failed to list modules directory: " .. modules_dir)
  end

  for file in handle:lines() do
    local mod_name = file:match("^(.+)%.lua$")
    if mod_name and mod_name ~= "titles" then  -- Skip helper files
      local module_path = modules_dir .. "/" .. file
      local f = io.open(module_path, "r")
      if f then
        local content = f:read("*all")
        f:close()
        
        -- Extract module name, description, and category from the spec table
        -- Look for patterns like: name = "git", description = "...", category = "..."
        local name_match = content:match('name%s*=%s*["\']([^"\']+)["\']') or mod_name
        local desc_match = content:match('description%s*=%s*["\']([^"\']+)["\']') or ""
        local cat_match = content:match('category%s*=%s*["\']([^"\']+)["\']') or "integration"
        
        local module_info = {
          name = name_match,
          description = desc_match,
          category = cat_match,
        }
        
        table.insert(modules, module_info)
      end
    end
  end

  handle:close()

  -- Sort modules by name
  table.sort(modules, function(a, b)
    return a.name < b.name
  end)

  return modules
end

local function generate_config_lua(modules)
  local lines = {
    "--[[",
    "  WezMacs Module Configuration",
    "",
    "  This file allows you to override module settings.",
    "  Format: { { \"module-name\", enabled = false, opts = { ... } } }",
    "",
    "  Examples:",
    "    { { \"claude\", enabled = false } }  -- Disable claude module",
    "    { { \"git\", opts = { leader_key = \"G\" } } }  -- Override git options",
    "",
    "  Generated by: wezmacs/generate-config.lua",
    "]]",
    "",
    "return {",
    "  -- Module overrides go here",
    "  -- Example: { { \"claude\", enabled = false } }",
    "}",
    "",
  }

  return table.concat(lines, "\n")
end

local function generate_setup_lua()
  local lines = {
    "--[[",
    "  WezMacs Custom Setup",
    "",
    "  This function is called after all module setup functions.",
    "  Use it to apply custom configuration that depends on module specs.",
    "",
    "  Parameters:",
    "    config - WezTerm config object",
    "    spec   - Map of all module specs: { module_name = spec, ... }",
    "",
    "  Example:",
    "    function setup(config, spec)",
    "      -- Access module spec: local git_spec = spec.git",
    "      -- Access module opts: local git_opts = spec.git.opts()",
    "      -- Modify config: config.custom_setting = true",
    "    end",
    "",
    "  Generated by: wezmacs/generate-config.lua",
    "]]",
    "",
    "return {",
    "  setup = function(config, spec)",
    "    -- Custom setup code goes here",
    "  end,",
    "}",
    "",
  }

  return table.concat(lines, "\n")
end

local function generate_keys_lua()
  local lines = {
    "--[[",
    "  WezMacs Custom Keybindings",
    "",
    "  This file defines custom keybindings that are applied after all module keys.",
    "  Return a nested map format: { LEADER = { key = { action = ..., desc = \"...\" } } }",
    "",
    "  Example:",
    "    return {",
    "      LEADER = {",
    "        x = {",
    "          action = wezmacs.action.ReloadConfiguration,",
    "          desc = \"custom/reload\",",
    "        },",
    "      },",
    "    }",
    "",
    "  Generated by: wezmacs/generate-config.lua",
    "]]",
    "",
    "return {}",
    "",
  }

  return table.concat(lines, "\n")
end

local function main()
  local output_dir = arg[1]
  if not output_dir then
    output_dir = get_config_dir()
  end

  -- Ensure output_dir ends without trailing slash
  output_dir = output_dir:gsub("/+$", "")

  print("Scanning modules...")
  local modules = scan_modules()
  print("Found " .. #modules .. " modules")

  print("Generating configuration files in: " .. output_dir)
  
  -- Create directory if needed
  os.execute("mkdir -p '" .. output_dir .. "'")

  -- Generate config.lua
  local config_content = generate_config_lua(modules)
  local config_path = output_dir .. "/config.lua"
  local f = io.open(config_path, "w")
  if not f then
    error("Failed to open output file: " .. config_path)
  end
  f:write(config_content)
  f:close()
  print("  ✓ Generated " .. config_path)

  -- Generate setup.lua
  local setup_content = generate_setup_lua()
  local setup_path = output_dir .. "/setup.lua"
  f = io.open(setup_path, "w")
  if not f then
    error("Failed to open output file: " .. setup_path)
  end
  f:write(setup_content)
  f:close()
  print("  ✓ Generated " .. setup_path)

  -- Generate keys.lua
  local keys_content = generate_keys_lua()
  local keys_path = output_dir .. "/keys.lua"
  f = io.open(keys_path, "w")
  if not f then
    error("Failed to open output file: " .. keys_path)
  end
  f:write(keys_content)
  f:close()
  print("  ✓ Generated " .. keys_path)

  print("")
  print("✓ Configuration files generated successfully")
  print("")
  print("Next steps:")
  print("1. Edit " .. output_dir .. "/config.lua to enable/disable modules")
  print("2. Edit " .. output_dir .. "/setup.lua for custom setup")
  print("3. Edit " .. output_dir .. "/keys.lua for custom keybindings")
  print("4. Reload WezTerm (Cmd+Option+R on macOS)")
end

main()
